// Code generated by MockGen. DO NOT EDIT.
// Source: ./notification.go
//
// Generated by this command:
//
//	mockgen -source=./notification.go -destination=./mocks/notification.mock.go -package=notificationmocks -typed Service
//

// Package notificationmocks is a generated GoMock package.
package notificationmocks

import (
	context "context"
	reflect "reflect"

	domain "github.com/robinlg/notification-platform/internal/domain"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// FindReadyNotifications mocks base method.
func (m *MockService) FindReadyNotifications(ctx context.Context, offset, limit int) ([]domain.Notification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindReadyNotifications", ctx, offset, limit)
	ret0, _ := ret[0].([]domain.Notification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindReadyNotifications indicates an expected call of FindReadyNotifications.
func (mr *MockServiceMockRecorder) FindReadyNotifications(ctx, offset, limit any) *MockServiceFindReadyNotificationsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindReadyNotifications", reflect.TypeOf((*MockService)(nil).FindReadyNotifications), ctx, offset, limit)
	return &MockServiceFindReadyNotificationsCall{Call: call}
}

// MockServiceFindReadyNotificationsCall wrap *gomock.Call
type MockServiceFindReadyNotificationsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockServiceFindReadyNotificationsCall) Return(arg0 []domain.Notification, arg1 error) *MockServiceFindReadyNotificationsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockServiceFindReadyNotificationsCall) Do(f func(context.Context, int, int) ([]domain.Notification, error)) *MockServiceFindReadyNotificationsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockServiceFindReadyNotificationsCall) DoAndReturn(f func(context.Context, int, int) ([]domain.Notification, error)) *MockServiceFindReadyNotificationsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
